### ISSUE TITLE
Cannel 7 Bit streaming

### ISSUE THREAD

**Issue by quarrantine** [tomhollander/IptvFtw#3]
Hello, Channel 7 not streaming on Aussie TV FTW. Thank you

**Comment by quarrantine** [comment]
Any updates yet? Thank you.

**Comment by tomhollander** [comment]
Can you just use IPTV FTW?

**Comment by quarrantine** [comment]
Hello Tom, I can switch but unsure on how to load all the channels. Do
you have a guide on how it can be done at all?

Thanks

**Comment by tomhollander** [comment]
For Australian channels, use the playlists documented at https://www.matthuisman.nz/2019/01/live-au-iptv-channels-on-android.html

**Comment by quarrantine** [comment]
Thank you very much. Have a great day.

**Comment by quarrantine** [comment]
Thank you all working now. Have a great day!!
