### ISSUE TITLE
Cannot stream Channel 7 Australia all states

### ISSUE THREAD

**Issue by quarrantine** [tomhollander/IptvFtw#5]
Hello Tom,

I have been advised to open this issue by Matt Huisman. 

Thanks

**Comment by quarrantine** [comment]
This is the url being used across all Australian states.

https://i.mjh.nz/au/Melbourne/kodi-tv.m3u8

Thank you

**Comment by tomhollander** [comment]
Why are you raising the issue here? I don't maintain the streaming URLs.

**Comment by quarrantine** [comment]
On the directive of Matt Huosman

**Comment by tomhollander** [comment]
Ok he is welcome to direct you, but I have no idea what to do with the issue. I can't fix it.

**Comment by quarrantine** [comment]
Seems like a handball game if you ask me!!

**Comment by tomhollander** [comment]
Please invite him to participate in this thread if I'm missing something. But I think the issue is with the steam, not my app.

**Comment by quarrantine** [comment]
Have just done so.

**Comment by matthuisman** [comment]
everyone would save a lot of time if users were clear with their bug issues....


Streaming url: https://i.mjh.nz/seven-ade.m3u8
which redirects to 7's actual url (https://csm-e-n7aus-eb.tls1.yospace.com/csm/extlive/sevenprd01,ADE1.m3u8?appId=7plus&deviceTyp.....)

In your windows app - it pauses / buffers playback after 1minute-ish

Works in VLC, Kodi + many other players

Steps to reproduce
1) open IPTV FTW
2) add url: https://i.mjh.nz/au/Adelaide/raw-tv.m3u8
3) Select "Seven" channel
4) wait and it will freeze

VLC at the same time on same stream = no freeze

**Comment by quarrantine** [comment]
Does look like issue is now resolved. A reply would have been nice.

**Comment by tomhollander** [comment]
I didn't break it and I didn't fix it, but you're welcome!

**Comment by quarrantine** [comment]
Very RUDE reply. Oh well will never support this person again!

**Comment by matthuisman** [comment]
I made no changes my end either.

im not sure how windows media apps work - but maybe this app calls a common Windows player api for playback.
Possibly windows pushed an update to fix that player core that IPTVFW uses.

The other possibility is that 7 themselves changed their manifests and those are now compatible.
We may never know!
